services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=payd"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=theolujay.dev@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - payd_letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - payd
    restart: unless-stopped

  db:
    image: postgres:17.2-bookworm
    volumes:
      - payd_db:/var/lib/postgresql/data
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - payd
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file: .env

  app:
    image: payd:prod
    build:
      context: .
    networks:
      - payd
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
    env_file: .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payd.rule=Host(`payd.theolujay.dev`)"
      - "traefik.http.routers.payd.entrypoints=websecure"
      - "traefik.http.routers.payd.tls.certresolver=le"
      - "traefik.http.routers.payd.tls=true"
      - "traefik.http.services.payd.loadbalancer.server.port=8000"

networks:
  payd:
    external: true

volumes:
  payd_db:
  payd_venv:
  payd_media:
  payd_static:
  payd_letsencrypt: