services:
  db:
    volumes:
      - payd_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - payd_dev
  app:
    image: payd:dev
    command: "python manage.py runserver"
    volumes:
      - .:/home/payd/app
      - payd_venv:/home/payd/app/.venv
      - payd_media:/home/payd/app/media
      - payd_static:/home/payd/app/staticfiles
    networks:
      - payd_dev
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db


networks:
  payd_dev:
    external: true

volumes:
  payd_db:
  payd_venv:
  payd_media:
  payd_static: