# Generated by Django 6.0 on 2025-12-10 04:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="paid_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("read", "Read Wallet & Transactions"),
                        ("deposit", "Create Deposits"),
                        ("transfer", "Initiate Transfers"),
                    ],
                    max_length=20,
                ),
                default=list,
                help_text="List of permissions this API key grants",
            ),
        ),
    ]
