# Generated by Django 6.0 on 2025-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_transaction_paid_at_alter_apikey_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
