# Generated by Django 6.0 on 2025-12-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(
                db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
