# Generated by Django 6.0 on 2025-12-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_transaction_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="lookup_hint",
            field=models.CharField(db_index=True, default=None, max_length=10),
            preserve_default=False,
        ),
    ]
