# Generated by Django 6.0 on 2025-12-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_apikey_lookup_hint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="wallet_number",
            field=models.IntegerField(unique=True),
        ),
    ]
