# Generated by Django 6.0 on 2025-12-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_wallet_wallet_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_number",
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["wallet_number"], name="api_wallet_wallet__f6e43f_idx"
            ),
        ),
    ]
